### ISSUE TITLE
Feature Suggest: Random planet at each landing

### ISSUE THREAD

**Issue by CmmmmmmLau** [stormytuna/RouteRandom#7] opened 2024-01-22 23:19 UTC
Hi, I like this mod could add more random challenges to the game when playing with my friend. 
But we found out if we don't go to termial and type `route random` again, the planet actually doesn't changed at next landing.
Maybe could add a new termial command like `route randomall`, then it will let the ship landing different planet everytime.

And another problem is the planet hide feature function is client side, so if someone's config set it to false. he could spoiler it.

**Comment by stormytuna** [comment] 2024-01-23 08:45
Using the terminal is the intended behaviour - I don't want it to be possible to try land and have the moon you're orbiting change 

Hiding the orbited planet could do with using the hosts options but it's such a minor issue I can't really be bothered setting up networking for it

Closing as I won't fix either of the issues mentioned here

**Closed as not planned by stormytuna** 2024-01-23 08:45 UTC

**Comment by BeepSterr** [comment] 2024-01-23 17:13
Shame.
