### ISSUE TITLE
Can not confirm for randomly chosen costly moon

### ISSUE THREAD

**Issue by NeuTraLZero** [stormytuna/RouteRandom#2] opened 2023-12-18 14:29 UTC
This is even when RemoveCostOfCostlyPlanets is set to true

**Comment by nickjuricic** [comment] 2023-12-28 23:03
I also have the same issue you described.

**Comment by Seathroath** [comment] 2024-01-02 01:28
i am also having this issue. The only way to by-pass it was to enable skip confirmation option.

**Comment by Ryu776** [comment] 2024-01-14 03:35
none of the configs seems to be working for me aside from the skip confirm

**Comment by stormytuna** [comment] 2024-01-22 20:28
Could you provide some more details, what exactly is the issue? Can you give any reproduction steps - what configs are enabled, what command do you type, what happens vs what you expect, etc

**Comment by darkanx** [comment] 2024-01-23 04:02
ALLOWED WEATHERS
all default
COSTLY PLANETS
AllowCostlyPlanets=true
RemoveCostOfCostyPlanets=true
GENERAL
SkipConfirmation=false
DifferentPlanetEachTime=false
HidePlanet=false

When you type in Random, it asks you to "confirm or deny", you are unable to hit return after typing in any confirmation. You can type a response, it just will not accept pressing enter.

Setting SkipConfirmation to true skips that step, thus working around the issue.

**Comment by stormytuna** [comment] 2024-01-23 09:45
Closing as fixed in [9b4b6c6](https://github.com/stormytuna/RouteRandom/commit/9b4b6c62fcfc5f6a3bd64080d632ecce70fdfdbb)

**Closed as completed by stormytuna** 2024-01-23 09:45 UTC
